###
GET http://localhost:3001/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmExZTNmNmJhYjBlM2JlOTdjYzIxMzIiLCJ1c2VybmFtZSI6ImFiaW5hbmRoYW4iLCJlbWFpbCI6ImFiaW5hbmRoYW41MDZAcHNuYWNldC5lZHUuaW4iLCJwaG9uZU51bWJlciI6IjgxMjI0NDE1NzQiLCJyb2xlIjoidXNlciIsImlhdCI6MTcyMjE4ODQzNywiZXhwIjoxNzIyMTkyMDM3fQ.K7L8xw6v9D_1CdI31AJDnl6PvLMWb8f8BjuklJYnjN8